[build]
  command = "ng build --prod"
  publish = "src" # Cambia esto a la carpeta donde está tu index.html, en este caso, src

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"